# Generated by Django 3.1.4 on 2020-12-19 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='description',
        ),
        migrations.AddField(
            model_name='food',
            name='prep_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='food',
            name='type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
