# Generated by Django 3.1.4 on 2020-12-19 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20201219_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='type',
            field=models.IntegerField(choices=[('warm_drinks', 'Топли напитки'), ('fizzy_drinks', 'Безалкохолни напитки'), ('beer', 'Пиво'), ('unknown', 'Твърд алкохол'), ('salads', 'Салати'), ('studeni_mezeta', 'Студени мезета'), ('topli_mezeta', 'Топли мезета'), ('meat', 'Скара'), ('sachove', 'Сачове'), ('nuts', 'Ядки')]),
        ),
    ]
