# Generated by Django 3.1.4 on 2020-12-19 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20201219_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='type',
            field=models.IntegerField(choices=[(0, 'Топли напитки'), (1, 'Безалкохолни напитки'), (2, 'Пиво'), (3, 'Твърд алкохол'), (4, 'Салати'), (5, 'Студени мезета'), (6, 'Топли мезета'), (7, 'Скара'), (8, 'Сачове'), (9, 'Ядки')]),
        ),
    ]
